### ISSUE TITLE
解决实验一rust-lld: error: undefined symbol: LD_STACK_PTR报错和couldn't find crate `core` with expected target triple aarch64-unknown-none-softfloat-5103292167306961306报错

### ISSUE THREAD

**Issue by zhiqiuyuan** [sotinyatgithub/os2022exps#1]
1. 编译命令修改为

   ```bash
   cargo build --target aarch64-unknown-none-softfloat.json
   ```

2. 项目目录下新建.cargo/config.toml文件，内容如下

   ```toml
   [unstable]
   build-std = ["core", "compiler_builtins"] 
   ```

原先编译命令

```bash
cargo build --target aarch64-unknown-none-softfloat
```

会报错如下：

> error: linking with `rust-lld` failed: exit status: 1
>   |
>   = note: "rust-lld" "-flavor" "gnu" "/home/yuanzhiqiu/os/yzqos_armv8/target/aarch64-unknown-none-softfloat/debug/deps/yzqos_armv8-b39476ede8baa276.358o59hkt7efruo.rcgu.o" "/home/yuanzhiqiu/os/yzqos_armv8/target/aarch64-unknown-none-softfloat/debug/deps/yzqos_armv8-b39476ede8baa276.4t21rnm557dy8f08.rcgu.o" "/home/yuanzhiqiu/os/yzqos_armv8/target/aarch64-unknown-none-softfloat/debug/deps/yzqos_armv8-b39476ede8baa276.51shtnl9jrmqr2vu.rcgu.o" "/home/yuanzhiqiu/os/yzqos_armv8/target/aarch64-unknown-none-softfloat/debug/deps/yzqos_armv8-b39476ede8baa276.5a7lwex1qifr7uk6.rcgu.o" "--as-needed" "-L" "/home/yuanzhiqiu/os/yzqos_armv8/target/aarch64-unknown-none-softfloat/debug/deps" "-L" "/home/yuanzhiqiu/os/yzqos_armv8/target/debug/deps" "-L" "/home/yuanzhiqiu/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/aarch64-unknown-none-softfloat/lib" "-Bstatic" "/home/yuanzhiqiu/os/yzqos_armv8/target/aarch64-unknown-none-softfloat/debug/deps/librustc_std_workspace_core-1dcf6d93b6d407a2.rlib" "/home/yuanzhiqiu/os/yzqos_armv8/target/aarch64-unknown-none-softfloat/debug/deps/libcore-1bf904a56375861d.rlib" "/home/yuanzhiqiu/os/yzqos_armv8/target/aarch64-unknown-none-softfloat/debug/deps/libcompiler_builtins-4f3ab19918958b56.rlib" "-Bdynamic" "--eh-frame-hdr" "-znoexecstack" "-L" "/home/yuanzhiqiu/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/aarch64-unknown-none-softfloat/lib" "-o" "/home/yuanzhiqiu/os/yzqos_armv8/target/aarch64-unknown-none-softfloat/debug/deps/yzqos_armv8-b39476ede8baa276" "--gc-sections"
>   = note: rust-lld: error: undefined symbol: LD_STACK_PTR
>           >>> referenced by 5a7lwex1qifr7uk6
>           >>>               /home/yuanzhiqiu/os/yzqos_armv8/target/aarch64-unknown-none-softfloat/debug/deps/yzqos_armv8-b39476ede8baa276.5a7lwex1qifr7uk6.rcgu.o:(.text.boot+0x18)
>           
>
> error: could not compile `yzqos_armv8` due to previous error

修改编译命令但不新增.cargo/config.toml文件的话报错如下：

> cargo build --target aarch64-unknown-none-softfloat.json
>    Compiling yzqos_armv8 v0.1.0 (/home/yuanzhiqiu/os/yzqos_armv8)
> warning: target json file contains unused fields: abi-blacklist
>
> error[E0461]: couldn't find crate `core` with expected target triple aarch64-unknown-none-softfloat-5103292167306961306
>   |
>   = note: the following crate versions were found:
>           crate `core`, target triple aarch64-unknown-none-softfloat: /home/yuanzhiqiu/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/aarch64-unknown-none-softfloat/lib/libcore-ac4407b588a64e53.rlib
>
> warning: `yzqos_armv8` (bin "yzqos_armv8") generated 1 warning
> error: could not compile `yzqos_armv8` due to previous error; 1 warning emitted

关于编译命令，想更为方便的话，可以如下配置：

.cargo/config.toml文件中添加内容：

```toml
[build]
target = "aarch64-unknown-none-softfloat.json"
```

则编译命令只需

```bash
cargo build
```

**Comment by noionion** [comment]
如果采用上述的修复方法，在实验4的时候引发中断输出后会阻塞。

1. 如果增加了armv8支持
```bash
$ rustup target add aarch64-unknown-none-softfloat
```

此时，如果在config中多加了
```toml
[unstable]
build-std = ["core", "compiler_builtins"] 
```
或者少加了
```toml
[build]
rustflags = ["-C","link-arg=-Taarch64-qemu.ld", "-C", "target-cpu=cortex-a53", "-D", "warnings"]
```
都会造成阻塞

2. 如果未加上armv8支持则需要`[unstable]`一项（基于本实验是移植blogos到armv8，这种方式是不建议的）

--------

阻塞的原因在于引发中断后无法输出`ctx`下的寄存器
```rust
// 调用print!宏打印异常信息，你也可以选择打印异常发生时所有寄存器的信息
fn catch(ctx: &mut ExceptionCtx, name: &str) {
    crate::print!(
        "\n  \
        {} @ 0x{:016x}\n",
        name, ctx.elr_el1,
    );
}
```
输出会堵在`@`

需要将整个config.toml文件替换成如下值（其实就是实验指导书原本的内容），编译命令直接用`cargo build`就行
```toml
[build]
target = "aarch64-unknown-none-softfloat.json"
rustflags = ["-C","link-arg=-Taarch64-qemu.ld", "-C", "target-cpu=cortex-a53", "-D", "warnings"]
```
